services:
  - type: web
    name: aibot
    env: docker
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "3600000"
      - key: JAVA_OPTS
        value: "-Xms256m -Xmx512m"
      # If you add a Render PostgreSQL (free) instance, it will expose DATABASE_URL automatically.
      # The container entrypoint parses DATABASE_URL into Spring's datasource vars.
