package AiBot.example.AiBot.service;

import org.springframework.stereotype.Service;

@Service
public class ChatService {
    
    public String generateResponse(String prompt) {
        // Mock implementation - in production this would call OpenAI API
        if (prompt.toLowerCase().contains("summarize")) {
            return "This is a mock summary of the document. In production, this would be generated by OpenAI's GPT model.";
        } else if (prompt.toLowerCase().contains("question")) {
            return "This is a mock answer to your question. In production, this would be generated by OpenAI's GPT model based on the document content.";
        } else {
            return "Mock AI response: " + prompt.substring(0, Math.min(prompt.length(), 100)) + "...";
        }
    }
}
